### ISSUE TITLE
Unable to Save image in iOS device using Photo Libraby

### ISSUE THREAD

**Issue by Pratikshakhandagale** [terikon/cordova-plugin-photo-library#173]
Error - ERROR: Method '**requestAuthorization**:' not defined in Plugin 'PhotoLibrary' and 
same issue facing for **SaveImage** Function.

Few details:
- Ionic 3
- Plugin version : PhotoLibrary ^2.2.1

Working fine in Android device but not working on iPhone 5s , iPhone 7(12.3.1) and other device.

**Comment by Scobee** [comment]
@Pratikshakhandagale how were you able to build this for IOS? After installing this plugin, I get an error:
[15:22:47]  ionic-app-script task: "build" 
[15:22:47]  TypeError: compiler_1.isFormattedError is not a function 
TypeError: compiler_1.isFormattedError is not a function
    at syntaxErrorToDiagnostics (/Volumes/Work/Projects/Adservio/adservioapp/node_modules/@angular/compiler-cli/src/transformers/program.js:798:25)
    at AngularCompilerProgram._addStructuralDiagnostics (/Volumes/Work/Projects/Adservio/adservioapp/node_modules/@angular/compiler-cli/src/transformers/program.js:485:49)
    at AngularCompilerProgram._createProgramOnError (/Volumes/Work/Projects/Adservio/adservioapp/node_modules/@angular/compiler-cli/src/transformers/program.js:477:18)
    at /Volumes/Work/Projects/Adservio/adservioapp/node_modules/@angular/compiler-cli/src/transformers/program.js:151:48
