### ISSUE TITLE
Will not build on android with Java 1.6

### ISSUE THREAD

**Issue by ETinLV** [terikon/cordova-plugin-photo-library#5]
I added this plugin to my project, and it works great for iOS, but Android will no longer build. I am getting:
```
/MyProject/platforms/android/src/com/terikon/cordova/photolibrary/PhotoLibraryService.java:78: error: diamond operator is not supported in -source 1.6
    ArrayList<JSONObject> results = new ArrayList<>();
```
Am I missing something?

Thanks!

**Comment by viskin** [comment]
You do it right. Just I use other java version.  To support Java 1.6 this library shouldn't use this syntax:

      ArrayList<JSONObject> results = new ArrayList<>();

But do the following instead:

      ArrayList<JSONObject> results = new ArrayList<JSONObject>();

Can you please manually change places in plugin where diamond operator is used in your project (in cordova/platforms/android), and tell me if it will solve the problem for you. If so, I can update the code to make it compatible with java 1.6. Or make a PR, I will merge it.
