### PR TITLE
make compatible with java 1.6

### LINKED ISSUE #5: Will not build on android with Java 1.6
I added this plugin to my project, and it works great for iOS, but Android will no longer build. I am getting:
```
/MyProject/platforms/android/src/com/terikon/cordova/photolibrary/PhotoLibraryService.java:78: error: diamond operator is not supported in -source 1.6
    ArrayList<JSONObject> results = new ArrayList<>();
```
Am I missing something?

Thanks!

### PR DESCRIPTION
**Pull request by ETinLV**
fixes #5 , Everything built again with java 1.6, working as expected

### CODE REVIEW

**Comment by viskin** [comment]
Great, thanks!
